repos:
-   repo: local
    hooks:
    -   id: requirements
        name: atualizando requirements.txt
        entry: bash -c "venv/bin/pip3 freeze > requirements.txt && git add requirements.txt"
        language: system
        pass_filenames: false
        stages: [pre-commit]