repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        name: Fomatando código com Black

repos:
-   repo: local
    hooks:
    -   id: requirements
        name: Atualizando requirements.txt
        entry: bash -c "venv/bin/pip3 freeze > requirements.txt && git add requirements.txt"
        language: system
        pass_filenames: false
        stages: [pre-commit]