repos:
-   repo: local
    hooks:
    -   id: requirements
        name: Atualizando requirements.txt
        entry: bash -c "venv/bin/pip3 freeze > requirements.txt && git add requirements.txt"
        language: system
        pass_filenames: false
        stages: [pre-commit]

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        name: Formatando código com Black
        stages: [pre-commit]